# Generated by Django 6.1 on 2026-08-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='map_x',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='map_y',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
