# Generated by Django 6.1 on 2026-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_country_map_x_country_map_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='lat',
            field=models.FloatField(blank=True, default=0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='country',
            name='lng',
            field=models.FloatField(blank=True, default=0, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='country',
            name='map_x',
            field=models.IntegerField(blank=True, default=0, verbose_name='Позиция на карте (X)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='map_y',
            field=models.IntegerField(blank=True, default=0, verbose_name='Позиция на карте (Y)'),
        ),
    ]
