# Generated by Django 6.1 on 2026-08-31 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_country_lat_country_lng_alter_country_map_x_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название склада')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('map_x', models.IntegerField(blank=True, default=0, verbose_name='Позиция на карте (X)')),
                ('map_y', models.IntegerField(blank=True, default=0, verbose_name='Позиция на карте (Y)')),
                ('lat', models.FloatField(blank=True, default=0, verbose_name='Широта')),
                ('lng', models.FloatField(blank=True, default=0, verbose_name='Долгота')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sklads', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин склада')),
            ],
        ),
    ]
