# Generated by Django 6.1 on 2026-08-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_add_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_notifications_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
