# Generated by Django 6.1 on 2026-08-31 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_profile_last_notifications_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='country',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='country',
            name='map_x',
        ),
        migrations.RemoveField(
            model_name='country',
            name='map_y',
        ),
    ]
