# Generated by Django 6.1 on 2026-08-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_country_lat_remove_country_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Город'),
        ),
    ]
